/**
 * TeX -> MathML, once, at build time.
 *
 * Writes src/generated/math.ts. Run by `bun run gen:math`, which `dev` and
 * `build` both depend on. Nothing from mathjax-full reaches the browser bundle:
 * the site ships plain MathML and lets the browser's math engine typeset it.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { liteAdaptor } from "mathjax-full/js/adaptors/liteAdaptor.js";
import { STATE } from "mathjax-full/js/core/MathItem.js";
import type { MmlNode } from "mathjax-full/js/core/MmlTree/MmlNode.js";
import { SerializedMmlVisitor } from "mathjax-full/js/core/MmlTree/SerializedMmlVisitor.js";
import { RegisterHTMLHandler } from "mathjax-full/js/handlers/html.js";
import { TeX } from "mathjax-full/js/input/tex.js";
import { AllPackages } from "mathjax-full/js/input/tex/AllPackages.js";
import { mathjax } from "mathjax-full/js/mathjax.js";

import { MATH } from "../src/content/math";

const here = dirname(fileURLToPath(import.meta.url));
const outFile = resolve(here, "../src/generated/math.ts");

RegisterHTMLHandler(liteAdaptor());

// Everything except bussproofs, whose extension hooks the document at load and
// demands an output jax with getBBox(). We stop before any output jax runs, so
// it would throw on startup; nothing here draws proof trees anyway. The rest of
// AllPackages covers ams (aligned, substack, pmatrix, \mathbb) and the base
// macros the papers use.
const packages = AllPackages.filter((name) => name !== "bussproofs");

const doc = mathjax.document("", { InputJax: new TeX({ packages }) });
const visitor = new SerializedMmlVisitor();

/**
 * mathjax.document() is declared as MathDocument<any, any, any>, so convert()
 * comes back as `any`. Rather than assert a type onto it, take it as `unknown`
 * and check: an MmlNode carries isKind() and childNodes, where the lite
 * adaptor's DOM element — what convert() returns if it runs past CONVERT —
 * carries neither. The guard is real, not a formality.
 */
function isMmlNode(value: unknown): value is MmlNode {
  return (
    typeof value === "object" &&
    value !== null &&
    "isKind" in value &&
    typeof value.isKind === "function" &&
    "childNodes" in value
  );
}

function toMathML(tex: string, display: boolean): string {
  // end at CONVERT: build the internal MathML tree, then serialise it. Going
  // further would invoke an output jax and produce HTML or SVG instead.
  const converted: unknown = doc.convert(tex, { display, end: STATE.CONVERT });
  if (!isMmlNode(converted)) {
    throw new Error(`expected a MathML tree for: ${tex.slice(0, 60)}`);
  }

  const mml = visitor.visitTree(converted);
  if (!mml.startsWith("<math")) {
    throw new Error(`unexpected MathML root for: ${tex.slice(0, 60)}`);
  }
  if (mml.includes("merror")) {
    throw new Error(`TeX failed to parse: ${tex.slice(0, 60)}`);
  }
  return mml;
}

// Object.entries keeps the value typed as MathSource, so nothing has to index
// the record with a plain string (which would need a cast to stay type-safe).
const sources = Object.entries(MATH);
const entries = sources.map(
  ([key, source]) =>
    `  ${JSON.stringify(key)}: ${JSON.stringify(
      toMathML(source.tex, source.display),
    )},`,
);

const banner = `// GENERATED by scripts/gen-math.ts — do not edit.
// Source of truth: src/content/math.ts. Regenerate with \`bun run gen:math\`.
import type { MathKey } from "@/content/math";

export const MATHML: Readonly<Record<MathKey, string>> = {
${entries.join("\n")}
};
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, banner, "utf8");

process.stdout.write(
  `gen:math  ${String(sources.length)} expressions -> src/generated/math.ts\n`,
);
